### ISSUE TITLE
Does not work for repos using GitLab subgroups (i.e. only works for `owner/name`)

### ISSUE THREAD

**Issue by myii** [coq/bot#120]
As discovered by @Zimmi48 in [this topic](https://coq.zulipchat.com/#narrow/stream/243318-coqbot-devs.20.26.20users/topic/How.20to.20troubleshoot.20coqbot.3F) in Zulip.

This was the `coqbot.toml` config that failed:

```toml
[mapping]
gitlab = "saltstack-formulas/formulas/github/saltstack-formulas/test-formula"
```

This was to work for:

* https://github.com/saltstack-formulas/test-formula => https://gitlab.com/saltstack-formulas/formulas/github/saltstack-formulas/test-formula

@Zimmi48 mentioned that coqbot only works for `owner/name` at the current time (which we eventually got working).
