### ISSUE TITLE
Removing (and changing?) the `coqbot.toml` does not work without intervention

### ISSUE THREAD

**Issue by myii** [coq/bot#121]
Linked to #120.  Was also discovered by @Zimmi48 in [this topic](https://coq.zulipchat.com/#narrow/stream/243318-coqbot-devs.20.26.20users/topic/How.20to.20troubleshoot.20coqbot.3F) in Zulip.

This was the `coqbot.toml` config that failed:

```toml
[mapping]
gitlab = "saltstack-formulas/formulas/github/saltstack-formulas/test-formula"
```
I had already removed this but it wasn't picked up by coqbot until @Zimmi48 restarted the bot:

> ... the data was not updated when you removed the file.
> So basically, I've restarted the bot to remove the data from memory.
